# Configuración de Netlify para Leadership App
[build]
  # Comando de build
  command = "pnpm run build"
  # Directorio donde se genera el build
  publish = "dist"

# Configuraciones de redirects y rewrites
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers para seguridad y cache
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
  # Permitimos carga de scripts de Google reCAPTCHA (v3 / enterprise) y recursos asociados
  # Permitimos carga de scripts y frames necesarias para reCAPTCHA v3/Enterprise
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com; script-src-elem 'self' https://www.google.com https://www.gstatic.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://www.google.com; frame-src 'self' https://www.google.com https://www.gstatic.com https://www.recaptcha.net; frame-src-elem 'self' https://www.google.com https://www.gstatic.com https://www.recaptcha.net"

# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para archivos específicos
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# No cache para index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Configuración para Forms (si usas Netlify Forms)
[build.environment]
  # Variables que estarán disponibles durante el build
  GENERATE_SOURCEMAP = "false"

# Configuración de funciones serverless (si las necesitas)
[functions]
  directory = "netlify/functions"

# Plugin para optimizaciones adicionales
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Configuración específica por entorno
[context.production]
  command = "pnpm run build"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "pnpm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"

[context.branch-deploy]
  command = "pnpm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "production"