export const mockQuestionary = {
  title_leader: 'DESARROLLO DE DESTREZAS DE DIRECCIÓN\nINVENTARIO DE PRÁCTICAS DE LIDERAZGO',
  title_collaborator: 'DESARROLLO DE DESTREZAS DE DIRECCIÓN\nINVENTARIO DE PRÁCTICAS DE LIDERAZGO',
  description_leader:
    'POR FAVOR PIENSE EN CÓMO USTED SUELE ACTUAR GENERALMENTE EN EL TRABAJO Y COLOQUE LA FRECUENCIA CON LA QUE DEMUESTRA LOS COMPORTAMIENTOS ENUNCIADOS.\n\n1: Rara vez o Nunca\n2: De vez en cuando\n3: Algunas veces\n4: Con frecuencia\n5: Muy frecuentemente',
  description_collaborator:
    'POR FAVOR PIENSE EN CÓMO USTED SUELE ACTUAR GENERALMENTE EN EL TRABAJO Y COLOQUE LA FRECUENCIA CON LA QUE DEMUESTRA LOS COMPORTAMIENTOS ENUNCIADOS.\n\n1: Rara vez o Nunca\n2: De vez en cuando\n3: Algunas veces\n4: Con frecuencia\n5: Muy frecuentemente',
  version_type: 'both',
  is_active: true,
  categories: [
    {
      id: 'cat_1760574502308',
      name: 'MODELAR EL CAMINO',
      order_index: 0,
    },
    {
      id: 'cat_1760574506828',
      name: 'INSPIRAR UNA VISIÓN COMPARTIDA',
      order_index: 1,
    },
    {
      id: 'cat_1760574510412',
      name: 'DESAFIAR EL PROCESO',
      order_index: 2,
    },
    {
      id: 'cat_1760574516133',
      name: 'CAPACITAR A OTROS PARA LA ACCIÓN',
      order_index: 3,
    },
    {
      id: 'cat_1760574518908',
      name: 'ESTIMULAR EMOTIVAMENTE',
      order_index: 4,
    },
  ],
  use_categories: true,
  questions: [
    {
      id: 'c7c7f1c7-e0f8-4ed9-84b9-606946062919',
      text_leader: 'Demuestro con mi ejemplo lo que espero de los miembros de mi equipo.',
      text_collaborator: 'Demuestra con su ejemplo lo que espera de los demás.',
      question_type: 'likert',
      category_id: 'cat_1760574502308',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 0,
      is_active: true,
    },
    {
      id: 'acd343dd-ce01-426d-a09f-575244379c43',
      text_leader:
        'Hablo con mi equipo sobre las tendencias futuras de la organización y como estas podrían influenciar nuestro trabajo. Describo a los demás el futuro que me gustaría crear junto con ellos',
      text_collaborator:
        'Habla sobre las tendencias futuras de la Organización y como estas podrían influenciar el trabajo del equipo. Describo a los demás el futuro que me gustaría crear junto con ellos',
      question_type: 'likert',
      category_id: 'cat_1760574506828',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 1,
      is_active: true,
    },
    {
      id: 'd579afd3-68c0-4afb-93ee-79f3021e85ce',
      text_leader: 'Busco oportunidades desafiantes que ponen a prueba mis propias habilidades y habilidades.',
      text_collaborator: 'Busca oportunidades desafiantes que ponen a prueba sus propias habilidades y habilidades.',
      question_type: 'likert',
      category_id: 'cat_1760574510412',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 2,
      is_active: true,
    },
    {
      id: '26fe2028-3c37-4ebf-86f1-b0a23b93a92a',
      text_leader: 'Desarrollo relaciones de cooperación con los miembros de mi equipo.',
      text_collaborator: 'Desarrolla relaciones de cooperación con el equipo de trabajo.',
      question_type: 'likert',
      category_id: 'cat_1760574516133',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 3,
      is_active: true,
    },
    {
      id: '33613ebf-37cb-42ee-8b45-7a69ca48335f',
      text_leader: 'Elogio a la gente cuando hace un buen trabajo',
      text_collaborator: 'Elogia a la gente cuando hace un buen trabajo',
      question_type: 'likert',
      category_id: 'cat_1760574518908',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 4,
      is_active: true,
    },
    {
      id: '64f5fc84-1a77-43a8-bd1c-34103f0b29db',
      text_leader: 'Gasto tiempo y energía para asegurarme que las personas cumplan los principios y estándares que hemos acordado.',
      text_collaborator:
        'Gasta tiempo y energía para asegurarse que los miembros del equipo cumplamos los principios y estándares que hemos acordado.',
      question_type: 'likert',
      category_id: 'cat_1760574502308',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 5,
      is_active: true,
    },
    {
      id: '9c74d030-4222-4e24-a378-cc0380ab884a',
      text_leader: 'Describo a los miembros de mi equipo una imagen convincente del futuro que me gustaría crear junto a ellos',
      text_collaborator: 'Suele dar una imagen convincente del futuro que le gustaría crear con el equipo de trabajo.',
      question_type: 'likert',
      category_id: 'cat_1760574506828',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 6,
      is_active: true,
    },
    {
      id: 'c43bb833-2bfe-4429-9746-553be9f950b0',
      text_leader: 'Incentivo y desafío a mis colaboradores para que busquen formas nuevas o innovadoras para hacer el trabajo',
      text_collaborator: 'Nos incentiva y desafía para que busquemos formas nuevas o innovadoras de hacer el trabajo',
      question_type: 'likert',
      category_id: 'cat_1760574510412',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 7,
      is_active: true,
    },
    {
      id: '5f2ae1a0-30b2-4ab8-8a13-b5b12fcbfcab',
      text_leader: 'Escucho activamente puntos de vista diferentes',
      text_collaborator: 'Escucha activamente puntos de vista diferentes',
      question_type: 'likert',
      category_id: 'cat_1760574516133',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 8,
      is_active: true,
    },
    {
      id: '15814492-8596-49fe-8c04-d628acc19dbd',
      text_leader: 'Busco que el personal a mi cargo desarrolle confianza en sus propias habilidades y capacidades',
      text_collaborator: 'Busca que el personal a su cargo desarrolle confianza en sus propias habilidades y capacidades',
      question_type: 'likert',
      category_id: 'cat_1760574518908',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 9,
      is_active: true,
    },
    {
      id: '89f8b095-a439-4b4d-b731-3cb95324ca89',
      text_leader: 'Cumplo las promesas y los compromisos que hago',
      text_collaborator: 'Cumple las promesas y los compromisos que hace.',
      question_type: 'likert',
      category_id: 'cat_1760574502308',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 10,
      is_active: true,
    },
    {
      id: '9605f43e-2eb2-4811-86ce-1c8df650fc95',
      text_leader: 'Demuestro motivación y entusiasmo contagioso sobre las posibilidades de futuro',
      text_collaborator: 'Demuestra motivación y entusiasmo contagioso sobre las posibilidades de futuro',
      question_type: 'likert',
      category_id: 'cat_1760574506828',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 11,
      is_active: true,
    },
    {
      id: 'bfebd536-a6a2-414b-a27f-f315b99b7139',
      text_leader: 'Busco maneras innovadoras que puedan mejorar los procesos actuales.',
      text_collaborator: 'Busca maneras innovadoras que puedan mejorar los procesos actuales.',
      question_type: 'likert',
      category_id: 'cat_1760574510412',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 12,
      is_active: true,
    },
    {
      id: '352f577c-eba9-4bd7-beaf-178cd58f1a9a',
      text_leader: 'Trato con dignidad y respecto a los miembros de mi equipo.',
      text_collaborator: 'Trata con dignidad y respecto a los demás',
      question_type: 'likert',
      category_id: 'cat_1760574516133',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 13,
      is_active: true,
    },
    {
      id: 'e5a76e7b-fac6-4d8f-9a4b-cbe8debae42a',
      text_leader: 'Me aseguro que mis colaboradores sean reconocidos por las contribuciones que realizan para el éxito del trabajo.',
      text_collaborator:
        'Se asegura que los miembros del equipo sean reconocidos por las contribuciones que realizan para el éxito del trabajo.',
      question_type: 'likert',
      category_id: 'cat_1760574518908',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 14,
      is_active: true,
    },
    {
      id: 'e7e376e4-d68d-4e2b-9265-e3bab0e933eb',
      text_leader: 'Pido que me den retroalimentación sobre cómo mis acciones afectan el rendimiento del equipo.',
      text_collaborator: 'Pide retroalimentación sobre cómo sus acciones afectan el rendimiento del equipo.',
      question_type: 'likert',
      category_id: 'cat_1760574502308',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 15,
      is_active: true,
    },
    {
      id: '66f0ac74-0d1c-40ad-b378-5d51ab679752',
      text_leader:
        'Demuestro a los miembros de mi equipo como las metas a largo plazo se pueden realizar mediante el compromiso con una visión compartida.',
      text_collaborator:
        'Demuestra a los miembros del equipo como las metas a largo plazo se pueden realizar mediante el compromiso con una visión compartida.',
      question_type: 'likert',
      category_id: 'cat_1760574506828',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 16,
      is_active: true,
    },
    {
      id: 'c489bf76-9335-4c5a-a26b-3033780915d6',
      text_leader: 'Cuando las cosas no salen como esperábamos pregunto: ¿qué podemos aprender?',
      text_collaborator: 'Cuando las cosas no salen como esperábamos pregunta: ¿qué podemos aprender?',
      question_type: 'likert',
      category_id: 'cat_1760574510412',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 17,
      is_active: true,
    },
    {
      id: 'c79878b1-1ab3-4013-996d-484b6321840b',
      text_leader: 'Apoyo las decisiones que mis colaboradores toman por sí mismos.',
      text_collaborator: 'Apoya las decisiones que los miembros del equipo toman por sí mismos.',
      question_type: 'likert',
      category_id: 'cat_1760574516133',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 18,
      is_active: true,
    },
    {
      id: '6d99f9d5-5c60-4417-895d-eacabb952565',
      text_leader: 'Reconozco públicamente a los miembros de mi equipo que dan ejemplo de compromiso con los valores de la organización.',
      text_collaborator:
        'Reconoce públicamente a los miembros del equipo que dan ejemplo de compromiso con los valores de la organización.',
      question_type: 'likert',
      category_id: 'cat_1760574518908',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 19,
      is_active: true,
    },
    {
      id: 'b8dfdae5-49a3-4012-83b5-0b6b9a5c5d40',
      text_leader: 'Establezco consenso con el equipo sobre los valores que debemos seguir en la organización.',
      text_collaborator: 'Establece consenso con el equipo sobre los valores que deben seguir en la organización.',
      question_type: 'likert',
      category_id: 'cat_1760574502308',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 20,
      is_active: true,
    },
    {
      id: 'b681aa95-dfe5-454d-afcb-846e616ba040',
      text_leader: 'Explico a mi personal el "cuadro grande" de lo que queremos alcanzar.',
      text_collaborator: 'Explica al equipo el "cuadro grande" de lo que se quiere alcanzar.',
      question_type: 'likert',
      category_id: 'cat_1760574506828',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 21,
      is_active: true,
    },
    {
      id: '76beb348-87af-45a3-a49d-f0e7a1c04c04',
      text_leader:
        'Me aseguro que las personas que trabajan conmigo tengan claro los objetivos del trabajo, elaboren planes y establezcan metas para el trabajo',
      text_collaborator:
        'Se asegura que las personas del equipo tengan claro los objetivos del trabajo, elaboren planes y establezcan metas para el trabajo',
      question_type: 'likert',
      category_id: 'cat_1760574510412',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 22,
      is_active: true,
    },
    {
      id: '1ce20d44-4485-4208-b5f1-5ae13639b948',
      text_leader: 'Otorgo bastante libertad a mi personal para decidir sobre la forma en que quieren realizar su trabajo',
      text_collaborator: 'Otorga bastante libertad al personal para decidir sobre la forma en que quieren realizar su trabajo',
      question_type: 'likert',
      category_id: 'cat_1760574516133',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 23,
      is_active: true,
    },
    {
      id: '7ec2388c-3331-4887-9847-12bcfea98563',
      text_leader: 'Celebro con el equipo las metas cumplidas',
      text_collaborator: 'Celebra con el equipo las metas cumplidas',
      question_type: 'likert',
      category_id: 'cat_1760574518908',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 24,
      is_active: true,
    },
    {
      id: 'fe23fde5-f354-4b8e-8942-ab60d8c3c728',
      text_leader: 'Estoy claro/a de cuál es mi filosofía de liderazgo',
      text_collaborator: 'Todos conocemos cuál es su filosofía de liderazgo',
      question_type: 'likert',
      category_id: 'cat_1760574502308',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 25,
      is_active: true,
    },
    {
      id: '43b3db0c-2dd1-49cd-a954-b6a1f1cdbd86',
      text_leader: 'Hablo con convicción sobre la trascendencia y el propósito del trabajo que hacemos',
      text_collaborator: 'Habla con convicción sobre la trascendencia y el propósito del trabajo que hacemos',
      question_type: 'likert',
      category_id: 'cat_1760574506828',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 26,
      is_active: true,
    },
    {
      id: 'bd179f3a-a1e8-4915-a673-617147e837dd',
      text_leader: 'Experimento y me arriesgo con nuevos enfoques en el trabajo, a pesar de que haya la posibilidad de que fallen',
      text_collaborator: 'Experimenta y se arriesgo con nuevos enfoques en el trabajo, a pesar de que haya la posibilidad de que fallen',
      question_type: 'likert',
      category_id: 'cat_1760574510412',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 27,
      is_active: true,
    },
    {
      id: '2f3d5462-b8fc-4db3-a180-6c0de0af1193',
      text_leader: 'Me aseguro de que mis colaboradores estén aprendiendo y desarrollando nuevas habilidades en el trabajo.',
      text_collaborator: 'Se asegura de que sus colaboradores estén aprendiendo y desarrollando nuevas habilidades en el trabajo.',
      question_type: 'likert',
      category_id: 'cat_1760574516133',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 28,
      is_active: true,
    },
    {
      id: '1d6acfbe-6161-4e72-a584-cab3d92efda2',
      text_leader: 'Demuestro mucho aprecio por el trabajo que hacen los miembros de mi equipo y doy soporte a las contribuciones hechas.',
      text_collaborator:
        'Demuestra mucho aprecio por el trabajo que hacen los miembros del equipo y da soporte a las contribuciones hechas.',
      question_type: 'likert',
      category_id: 'cat_1760574518908',
      response_config: {
        scale: 5,
        min_label: 'Rara vez o Nunca',
        max_label: 'Muy frecuentemente',
      },
      order_index: 29,
      is_active: true,
    },
  ],
};
