// Datos de prueba para la vista previa del PDF
export const mockData = {
    teamName: 'Equipo de Desarrollo',
    comparativeDataLength: 30,

    categorySummary: [
        {
            category: 'MODELAR EL CAMINO',
            auto_total: 24.0,
            otros_total: 20.0,
        },
        {
            category: 'INSPIRAR UNA VISIÓN COMPARTIDA',
            auto_total: 22.0,
            otros_total: 18.0,
        },
        {
            category: 'DESAFIAR EL PROCESO',
            auto_total: 22.0,
            otros_total: 20.0,
        },
        {
            category: 'CAPACITAR A OTROS PARA LA ACCIÓN',
            auto_total: 24.0,
            otros_total: 16.0,
        },
        {
            category: 'ESTIMULAR EMOTIVAMENTE',
            auto_total: 21.0,
            otros_total: 19.0,
        },
    ],

    categoryData: [
        {
            category: {
                id: '1',
                name: 'MODELAR EL CAMINO',
                description: 'Las palabras y los planes no son suficientes. El Líder tiene que demostrar sus creencias. Hay que practicar lo que se predica.',
                color: '#1976d2',
                order_index: 1,
            },
            leader_total: 24.0,
            collaborator_total: 20.0,
            questions: [
                {
                    question_id: '1',
                    question_text: 'Establezco un ejemplo personal de lo que espero de otros.',
                    question_number: 1,
                    leader_avg: 4.2,
                    collaborator_avg: 3.8,
                    leader_responses: [4, 4, 5, 4, 4],
                    collaborator_responses: [4, 3, 4, 4, 4],
                    average_collaborator: 3.8,
                },
                {
                    question_id: '2',
                    question_text: 'Dedico tiempo y esfuerzo para asegurarme de que las personas que dirijo acaten los principios y estándares que hemos acordado.',
                    question_number: 2,
                    leader_avg: 4.0,
                    collaborator_avg: 3.6,
                    leader_responses: [4, 4, 4, 4, 4],
                    collaborator_responses: [3, 4, 4, 3, 4],
                    average_collaborator: 3.6,
                },
                {
                    question_id: '3',
                    question_text: 'Sigo los compromisos y promesas que hago.',
                    question_number: 3,
                    leader_avg: 4.5,
                    collaborator_avg: 4.2,
                    leader_responses: [5, 4, 5, 4, 5],
                    collaborator_responses: [4, 4, 4, 5, 4],
                    average_collaborator: 4.2,
                },
                {
                    question_id: '4',
                    question_text: 'Pido retroalimentación sobre cómo mis acciones afectan el desempeño de otras personas.',
                    question_number: 4,
                    leader_avg: 3.8,
                    collaborator_avg: 3.4,
                    leader_responses: [4, 3, 4, 4, 4],
                    collaborator_responses: [3, 3, 4, 3, 4],
                    average_collaborator: 3.4,
                },
                {
                    question_id: '5',
                    question_text: 'Construyo consenso alrededor de una filosofía común y un conjunto de valores.',
                    question_number: 5,
                    leader_avg: 4.1,
                    collaborator_avg: 3.8,
                    leader_responses: [4, 4, 4, 4, 5],
                    collaborator_responses: [4, 3, 4, 4, 4],
                    average_collaborator: 3.8,
                },
                {
                    question_id: '6',
                    question_text: 'Expreso mis convicciones sobre el significado y propósito del trabajo que realizamos.',
                    question_number: 6,
                    leader_avg: 3.9,
                    collaborator_avg: 3.2,
                    leader_responses: [4, 4, 4, 3, 4],
                    collaborator_responses: [3, 3, 3, 4, 3],
                    average_collaborator: 3.2,
                },
            ],
        },
        {
            category: {
                id: '2',
                name: 'INSPIRAR UNA VISIÓN COMPARTIDA',
                description: 'Los líderes tienen puesta la mira en el futuro, visiones ideales de cómo quieren que sean las cosas.',
                color: '#388e3c',
                order_index: 2,
            },
            leader_total: 22.0,
            collaborator_total: 18.0,
            questions: [
                {
                    question_id: '7',
                    question_text: 'Hablo con otros sobre mi visión del futuro.',
                    question_number: 7,
                    leader_avg: 3.8,
                    collaborator_avg: 3.2,
                    leader_responses: [4, 3, 4, 4, 4],
                    collaborator_responses: [3, 3, 3, 4, 3],
                    average_collaborator: 3.2,
                },
                {
                    question_id: '8',
                    question_text: 'Describo una imagen convincente de cómo podríamos ser en el futuro.',
                    question_number: 8,
                    leader_avg: 3.6,
                    collaborator_avg: 3.0,
                    leader_responses: [3, 4, 4, 3, 4],
                    collaborator_responses: [3, 3, 3, 3, 3],
                    average_collaborator: 3.0,
                },
                {
                    question_id: '9',
                    question_text: 'Apelo a otros para que compartan un sueño emocionante del futuro.',
                    question_number: 9,
                    leader_avg: 3.7,
                    collaborator_avg: 2.8,
                    leader_responses: [4, 3, 4, 4, 3],
                    collaborator_responses: [3, 2, 3, 3, 3],
                    average_collaborator: 2.8,
                },
                {
                    question_id: '10',
                    question_text: 'Muestro a otros cómo se pueden realizar sus intereses a largo plazo mediante el compromiso con una visión común.',
                    question_number: 10,
                    leader_avg: 3.5,
                    collaborator_avg: 3.0,
                    leader_responses: [3, 4, 3, 4, 3],
                    collaborator_responses: [3, 3, 3, 3, 3],
                    average_collaborator: 3.0,
                },
                {
                    question_id: '11',
                    question_text: 'Pinto el "panorama general" de lo que aspiramos lograr.',
                    question_number: 11,
                    leader_avg: 3.9,
                    collaborator_avg: 3.4,
                    leader_responses: [4, 4, 4, 3, 4],
                    collaborator_responses: [3, 4, 3, 4, 3],
                    average_collaborator: 3.4,
                },
                {
                    question_id: '12',
                    question_text: 'Hablo con convicción sobre el significado y propósito más amplio de nuestro trabajo.',
                    question_number: 12,
                    leader_avg: 3.5,
                    collaborator_avg: 3.6,
                    leader_responses: [3, 4, 3, 4, 3],
                    collaborator_responses: [4, 3, 4, 3, 4],
                    average_collaborator: 3.6,
                },
            ],
        },
        {
            category: {
                id: '3',
                name: 'DESAFIAR EL PROCESO',
                description: 'Los líderes buscan y aceptan las oportunidades de probar sus habilidades. Los líderes experimentan, toman riesgos y aprenden de la experiencia.',
                color: '#f57c00',
                order_index: 3,
            },
            leader_total: 22.0,
            collaborator_total: 20.0,
            questions: [
                {
                    question_id: '13',
                    question_text: 'Busco oportunidades desafiantes que pongan a prueba mis propias habilidades y las de otros.',
                    question_number: 13,
                    leader_avg: 4.0,
                    collaborator_avg: 3.8,
                    leader_responses: [4, 4, 4, 4, 4],
                    collaborator_responses: [4, 3, 4, 4, 4],
                    average_collaborator: 3.8,
                },
                {
                    question_id: '14',
                    question_text: 'Desafío a las personas a probar enfoques nuevos e innovadores para su trabajo.',
                    question_number: 14,
                    leader_avg: 3.8,
                    collaborator_avg: 3.6,
                    leader_responses: [4, 3, 4, 4, 4],
                    collaborator_responses: [3, 4, 4, 3, 4],
                    average_collaborator: 3.6,
                },
                {
                    question_id: '15',
                    question_text: 'Busco maneras de mejorar todo lo que hacemos.',
                    question_number: 15,
                    leader_avg: 4.2,
                    collaborator_avg: 4.0,
                    leader_responses: [4, 5, 4, 4, 4],
                    collaborator_responses: [4, 4, 4, 4, 4],
                    average_collaborator: 4.0,
                },
                {
                    question_id: '16',
                    question_text: 'Pregunto "¿Qué podemos aprender?" cuando las cosas no salen como se esperaba.',
                    question_number: 16,
                    leader_avg: 3.6,
                    collaborator_avg: 3.2,
                    leader_responses: [3, 4, 4, 3, 4],
                    collaborator_responses: [3, 3, 3, 4, 3],
                    average_collaborator: 3.2,
                },
                {
                    question_id: '17',
                    question_text: 'Me aseguro de que establezcamos metas alcanzables, hagamos planes concretos y fijemos etapas medibles para los proyectos y programas que dirigimos.',
                    question_number: 17,
                    leader_avg: 3.7,
                    collaborator_avg: 3.4,
                    leader_responses: [4, 3, 4, 4, 3],
                    collaborator_responses: [3, 4, 3, 3, 4],
                    average_collaborator: 3.4,
                },
                {
                    question_id: '18',
                    question_text: 'Experimento y tomo riesgos, aunque exista la posibilidad de fracasar.',
                    question_number: 18,
                    leader_avg: 3.7,
                    collaborator_avg: 4.0,
                    leader_responses: [3, 4, 4, 3, 4],
                    collaborator_responses: [4, 4, 4, 4, 4],
                    average_collaborator: 4.0,
                },
            ],
        },
    ],
};